### PR TITLE
Fix vertical line clipping

### PR DESCRIPTION
**Pull request by ideasman42**
Correct min/max for vertical line

### CODE REVIEW

**Comment by salkinium** [comment]
Original author here. I moved this project over to https://github.com/salkinium/upainter, but broke the fork link cos I did it wrong. This repo is an old fork and should be deleted. Cc @ekiwi

**Comment by salkinium** [comment]
If you want I can cherry-pick your changes directly into the new repo, or you can create a new PR there, but I can't maintain this repo, cos it's not mine.

**Comment by ekiwi** [comment]
Yes. Thank you for your contribution. It would be great if you could open a PR with @salkinium's repository. Sorry for leaving this repo open.

**Comment by ideasman42** [comment]
eeeh. my bad! Was reading over this code, and assumed it was a mistake that top/bottom were flipped, infact top in this case has a lower y which confused me  - so think this can be ignored.

**Comment by salkinium** [comment]
No worries! Anyone reading this code is welcome to comment ;-P

Note that the algorithm isn't mine, it was published in a paper, that unfortunately isn't available publicly (last time I checked).

**Comment by ideasman42** [comment]
In case you're interested - posted this answer http://stackoverflow.com/a/40902741/432509

(answer to my own question since I needed to solve this problem).

**Pull request closed without merging**
